name: Compare Databases

on:
  pull_request:
    branches:
      - test
    paths:
      - 'awesome/database/data.db'

jobs:
  compare-dbs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SQLite
      run: sudo apt-get install sqlite3

    - name: Convert current branch database to dump
      run: sqlite3 awesome/database/data.db .dump > awesome/database/current_data.dump
      continue-on-error: true

    - name: Checkout target branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Convert target branch database to dump
      run: sqlite3 awesome/database/data.db .dump > awesome/database/target_data.dump
      continue-on-error: true

    - name: Show differences
      run: diff -a awesome/database/current_data.dump awesome/database/target_data.dump
